<%@ Page Title="" Language="C#" MasterPageFile="~/Site2.Master" AutoEventWireup="true" CodeBehind="contactus.aspx.cs" Inherits="masterpage.contactus" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2 style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-weight: 500; line-height: 1.2; font-size: 32px; font-family: Raleway, sans-serif; color: rgb(255, 255, 255); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 153, 51); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Contact Us</h2>
    <div class="address" style="box-sizing: border-box; color: rgb(68, 68, 68); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h4 style="box-sizing: border-box; margin-top: 0px; margin-bottom: 5px; font-weight: 600; line-height: 1.2; font-size: 22px; font-family: Raleway, sans-serif; padding: 0px 0px 0px 60px; color: rgb(55, 66, 59);">Location:</h4>
        <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px 0px 0px 60px; font-size: 14px; color: rgb(101, 122, 109);">
            2nd Floor, Fortune Mall, Munje Square, Sitabuldi, Nagpur, MH - 440013<br style="box-sizing: border-box;" />
            <br style="box-sizing: border-box;" />
        </p>
    </div>
    <div class="email" style="box-sizing: border-box; margin-top: 40px; color: rgb(68, 68, 68); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <i class="bi bi-envelope" style="box-sizing: border-box; font-size: 20px; color: rgb(0, 153, 51); float: left; width: 44px; height: 44px; background: rgb(236, 249, 240); display: flex; justify-content: center; align-items: center; border-radius: 50px; transition: all 0.3s ease-in-out 0s;"></i>
        <h4 style="box-sizing: border-box; margin-top: 0px; margin-bottom: 5px; font-weight: 600; line-height: 1.2; font-size: 22px; font-family: Raleway, sans-serif; padding: 0px 0px 0px 60px; color: rgb(55, 66, 59);">Email:</h4>
        <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px 0px 0px 60px; font-size: 14px; color: rgb(101, 122, 109);">
            support@mkpits.in<br style="box-sizing: border-box;" />
            jobs@mkpits.in</p>
    </div>
    <div class="phone" style="box-sizing: border-box; margin-top: 40px; color: rgb(68, 68, 68); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <i class="bi bi-phone" style="box-sizing: border-box; font-size: 20px; color: rgb(0, 153, 51); float: left; width: 44px; height: 44px; background: rgb(236, 249, 240); display: flex; justify-content: center; align-items: center; border-radius: 50px; transition: all 0.3s ease-in-out 0s;"></i>
        <h4 style="box-sizing: border-box; margin-top: 0px; margin-bottom: 5px; font-weight: 600; line-height: 1.2; font-size: 22px; font-family: Raleway, sans-serif; padding: 0px 0px 0px 60px; color: rgb(55, 66, 59);">Call:</h4>
        <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px 0px 0px 60px; font-size: 14px; color: rgb(101, 122, 109);">
            +91-78880-66630</p>
    </div>
</asp:Content>
